uploads = []
generated = []

[[outputs]]
id = "6ZqSzR_uR6yWKN6uAptHn"
uri = "file://artifacts/kkotbonabo/src/assets/images/profile_1.jpg"
type = "image"
title = "aesthetic candid young korean adult natural light film grain style"

[[outputs]]
id = "6eicivVlkbd_f5AQecqiv"
uri = "file://artifacts/kkotbonabo/src/assets/images/profile_2.jpg"
type = "image"
title = "aesthetic candid young korean adult natural light film grain style"

[[outputs]]
id = "Nck5ONYGeOfdmNOlLQHCN"
uri = "file://artifacts/kkotbonabo/src/assets/images/profile_3.jpg"
type = "image"
title = "aesthetic candid young korean adult natural light film grain style"

[[outputs]]
id = "nLu3qfAGaAgmML02a3c85"
uri = "file://attached_assets/image_search/cam_4_vintage-camera-texture.jpg"
type = "image"
title = "④ 빈티지 카메라, 질감"

[[outputs]]
id = "J9_RMQBrvCOl451bmUGJI"
uri = "file://attached_assets/image_search/cam_5_film-camera-dreamy.jpg"
type = "image"
title = "⑤ 필름 카메라, 몽환적"

[[outputs]]
id = "YGkNfNt12C-oA1y7remBh"
uri = "file://attached_assets/image_search/cam_6_camera-shadow-light.jpg"
type = "image"
title = "⑥ 카메라 + 빛과 그림자"

[[outputs]]
id = "_eK1pPEh67szMaw-87p9u"
uri = "file://attached_assets/image_search/cf_1_camera-flowers-1.jpg"
type = "image"
title = "① 카메라 + 꽃 A"

[[outputs]]
id = "yAv55D5yOf_cPCvleaq70"
uri = "file://attached_assets/image_search/cf_2_camera-flowers-2.jpg"
type = "image"
title = "② 카메라 + 꽃 B"

[[outputs]]
id = "VWvh9vBlOg0NCIGhisa3N"
uri = "file://attached_assets/image_search/cf_3_camera-flowers-3.jpg"
type = "image"
title = "③ 카메라 + 꽃 C"

[[outputs]]
id = "zW1ZV2dWz4gyLl_U00iPu"
uri = "file://attached_assets/image_search/light_3_벚꽃-빛번짐.jpg"
type = "image"
title = "③ 벚꽃 + 보케 빛"
